trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  rg: zaksud-rg
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    #- task: WhiteSource@21
    #  inputs:
    #    cwd: '$(System.DefaultWorkingDirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    environment: Dev
    strategy: 
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Azure for Students(8a625f6d-518c-4254-8e23-7c08e01e1d45)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  # Create a resource group
                  az group create --location northeurope --name $(rg)
                  
                  # Create an app service plan of type Linux
                  az appservice plan create -g $(rg) -n myapp-service-plan --is-linux
                  
                  # Create an App Service from the plan with Java SE as the runtime
                  az webapp create -g $(rg) -p myapp-service-plan -n zak-sudcloud --runtime "JAVA|8-jre8"
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Azure for Students(8a625f6d-518c-4254-8e23-7c08e01e1d45)'
                appType: 'webAppLinux'
                WebAppName: 'zak-sudcloud'
                packageForLinux: '$(Pipeline.Workspace)/**/*.jar'